[build]
  base = "./"
  command = "npm run build"
  publish = "build"
  environment = { SECRETS_SCAN_ENABLED = "false" }

# Ensure SPA routes serve index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
